# Generated by Django 5.1.4 on 2026-05-02 04:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("communes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("AGENT_FINANCIER", "Agent Financier"),
                            ("MAIRE", "Maire / Conseil Municipal"),
                            ("DGDDL", "DGDDL (Super Admin)"),
                            ("COUR_COMPTES", "Cour des Comptes"),
                            ("BAILLEUR", "Bailleur de Fonds"),
                            ("CITOYEN", "Citoyen"),
                            ("JOURNALISTE", "Journaliste"),
                        ],
                        default="CITOYEN",
                        max_length=20,
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(blank=True, default="", max_length=42),
                ),
                ("telephone", models.CharField(blank=True, default="", max_length=20)),
                (
                    "media_organisation",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("journaliste_verifie", models.BooleanField(default=False)),
                ("email_verifie", models.BooleanField(default=False)),
                ("avatar", models.URLField(blank=True, default="")),
                ("reputation_score", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agents",
                        to="communes.commune",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "db_table": "users",
            },
        ),
    ]
