# Generated by Django 5.1.4 on 2026-05-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profession",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CITOYEN", "Citoyen"),
                    ("JOURNALISTE", "Journaliste"),
                    ("ONG", "ONG / Société civile"),
                    ("CHERCHEUR", "Chercheur"),
                    ("AUTRE", "Autre"),
                ],
                default="CITOYEN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("AGENT_FINANCIER", "Agent Financier"),
                    ("MAIRE", "Maire / Conseil Municipal"),
                    ("DGDDL", "DGDDL (Super Admin)"),
                    ("COUR_COMPTES", "Cour des Comptes"),
                    ("BAILLEUR", "Bailleur de Fonds"),
                    ("CITOYEN", "Citoyen"),
                    ("JOURNALISTE", "Journaliste (déprécié → CITOYEN+profession)"),
                ],
                default="CITOYEN",
                max_length=20,
            ),
        ),
    ]
