# Generated by Django 5.2.10 on 2026-05-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_profession_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_blockchain_authorized",
            field=models.BooleanField(default=False),
        ),
    ]
