# Generated by Django 5.1.4 on 2026-05-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_blockchain_authorized"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="professions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste des professions additionnelles",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profession",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CITOYEN", "Citoyen"),
                    ("JOURNALISTE", "Journaliste"),
                    ("ONG", "ONG / Société civile"),
                    ("CHERCHEUR", "Chercheur"),
                    ("BAILLEUR", "Bailleur de Fonds"),
                    ("AUTRE", "Autre"),
                ],
                default="CITOYEN",
                max_length=20,
            ),
        ),
    ]
