# Generated by Django 5.1.4 on 2026-05-11 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_professions_alter_user_profession"),
    ]

    operations = [
        migrations.CreateModel(
            name="Engagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vote", "Vote Projet"),
                            ("signalement", "Signalement"),
                            ("participation", "Participation"),
                            ("commentaire", "Commentaire"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Complété"),
                            ("pending", "En attente"),
                            ("processing", "En cours de traitement"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "proof_hash",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Engagement",
                "verbose_name_plural": "Engagements",
                "db_table": "engagements",
                "ordering": ["-date"],
            },
        ),
    ]
