# Generated by Django 5.1.4 on 2026-05-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_profession_documents_and_databases"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="professiondocument",
            new_name="profession__user_id_172d43_idx",
            old_name="profession_doc_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="professiondocument",
            new_name="profession__profess_c751e1_idx",
            old_name="profession_doc_prof_status_idx",
        ),
        migrations.RenameIndex(
            model_name="verifiedong",
            new_name="verified_on_pays_ae2fb4_idx",
            old_name="verified_ong_pays_idx",
        ),
    ]
