# Generated by Django 5.1.4 on 2026-05-11 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0008_rename_profession_doc_user_status_idx_profession__user_id_172d43_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="certification_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin qui a vérifié cette certification",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_certifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="certification_reviewed_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="certification_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("APPROVED", "Approuvé"),
                    ("REJECTED", "Rejeté"),
                ],
                default="PENDING",
                help_text="Statut de la demande de certification Sentinelle",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cni_date_expiration",
            field=models.DateField(
                blank=True, help_text="Date d'expiration du document", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cni_numero",
            field=models.CharField(
                blank=True, default="", help_text="Numéro CNI/Passeport", max_length=50
            ),
        ),
    ]
