# Generated by Django 5.1.4 on 2026-05-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_certification_reviewed_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="certification_status",
            field=models.CharField(
                choices=[
                    ("NONE", "Non soumis"),
                    ("PENDING", "En attente"),
                    ("APPROVED", "Approuvé"),
                    ("REJECTED", "Rejeté"),
                ],
                default="NONE",
                help_text="Statut de la demande de certification Sentinelle",
                max_length=20,
            ),
        ),
    ]
