# Generated by Django 5.1.4 on 2026-05-02 04:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("DEPENSE", "Dépense"), ("RECETTE", "Recette")],
                        max_length=10,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("SOUMIS", "Soumis (en attente de validation)"),
                            ("VALIDE", "Validé sur blockchain"),
                            ("REJETE", "Rejeté"),
                        ],
                        default="BROUILLON",
                        max_length=20,
                    ),
                ),
                ("montant_fcfa", models.BigIntegerField()),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("INFRASTRUCTURE", "Infrastructure"),
                            ("SANTE", "Santé"),
                            ("EDUCATION", "Éducation"),
                            ("EAU_ASSAINISSEMENT", "Eau & Assainissement"),
                            ("SECURITE", "Sécurité"),
                            ("ADMINISTRATION", "Administration"),
                            ("AGRICULTURE", "Agriculture"),
                            ("CULTURE_SPORT", "Culture & Sport"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "periode",
                    models.CharField(
                        help_text="Format : YYYY-MM (ex: 2025-01)", max_length=7
                    ),
                ),
                ("ipfs_hash", models.CharField(blank=True, default="", max_length=100)),
                ("ipfs_url", models.URLField(blank=True, default="")),
                (
                    "blockchain_tx_hash_soumission",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "blockchain_tx_hash_validation",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("blockchain_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="communes.commune",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
