# Generated by Django 5.1.4 on 2026-05-02 20:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communes', '0001_initial'),
        ('transactions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('sujet', models.CharField(default='Anomalie financière', max_length=200)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to=settings.AUTH_USER_MODEL)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='communes.commune')),
            ],
            options={
                'db_table': 'signalements',
                'ordering': ['-created_at'],
            },
        ),
    ]
