# Generated by Django 5.2.10 on 2026-05-09 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_signalement"),
    ]

    operations = [
        migrations.AddField(
            model_name="signalement",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="Transaction spécifique concernée (optionnel)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signalements",
                to="transactions.transaction",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="motif_rejet",
            field=models.TextField(
                blank=True, default="", help_text="Explication du Maire en cas de rejet"
            ),
        ),
    ]
