# Generated by Django 5.2.10 on 2026-05-09 11:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communes", "0002_projet"),
        ("transactions", "0004_signalement_transaction_transaction_motif_rejet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PreuveSignalement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ipfs_hash", models.CharField(max_length=100)),
                ("ipfs_url", models.URLField()),
                (
                    "nom_fichier",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "type_fichier",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("pdf", "PDF"),
                            ("autre", "Autre"),
                        ],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "signalement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preuves",
                        to="transactions.signalement",
                    ),
                ),
            ],
            options={
                "db_table": "preuves_signalements",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PropositionDepense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("INFRASTRUCTURE", "Infrastructure"),
                            ("SANTE", "Santé"),
                            ("EDUCATION", "Éducation"),
                            ("EAU_ASSAINISSEMENT", "Eau & Assainissement"),
                            ("SECURITE", "Sécurité"),
                            ("ADMINISTRATION", "Administration"),
                            ("AGRICULTURE", "Agriculture"),
                            ("CULTURE_SPORT", "Culture & Sport"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=50,
                    ),
                ),
                ("budget_demande_fcfa", models.BigIntegerField(default=0)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active (en cours de vote)"),
                            ("VALIDEE", "Validée communautairement"),
                            ("REJETEE", "Rejetée"),
                            ("EXPIREE", "Expirée"),
                            ("CONVERTIE", "Convertie en transaction"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("deadline_vote", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propositions",
                        to="communes.commune",
                    ),
                ),
                (
                    "soumis_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="propositions_soumises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "propositions_depenses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoteProposition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_vote",
                    models.CharField(
                        choices=[("SOUTIEN", "Soutien"), ("OPPOSITION", "Opposition")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "citoyen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes_propositions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="transactions.propositiondepense",
                    ),
                ),
            ],
            options={
                "db_table": "votes_propositions",
                "unique_together": {("proposition", "citoyen")},
            },
        ),
    ]
