# Generated by Django 5.2.10 on 2026-05-09 11:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_phase1_preuves_propositions_votes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titre", models.CharField(max_length=150)),
                ("message", models.TextField()),
                (
                    "type_notif",
                    models.CharField(
                        choices=[
                            ("TRANSACTION", "Transaction"),
                            ("VOTE", "Vote"),
                            ("PROPOSITION", "Proposition"),
                            ("SIGNALEMENT", "Signalement"),
                            ("SYSTEME", "Système"),
                        ],
                        default="SYSTEME",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
