# Generated by Django 5.2.10 on 2026-05-09 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communes", "0003_projet_blockchain_audit_hash_alter_projet_statut"),
        ("transactions", "0006_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RapportPDF",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "periode",
                    models.CharField(help_text="Ex: Janvier 2026", max_length=20),
                ),
                ("ipfs_hash", models.CharField(blank=True, default="", max_length=100)),
                ("ipfs_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports_pdf",
                        to="communes.commune",
                    ),
                ),
                (
                    "genere_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rapports_generes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rapports_pdf",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjetTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liens_transactions",
                        to="communes.projet",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projets_lies",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "projets_transactions",
                "unique_together": {("projet", "transaction")},
            },
        ),
        migrations.CreateModel(
            name="VoteSignalement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[("CREDIBLE", "Crédible"), ("INFONDE", "Infondé")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "citoyen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes_signalements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signalement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="transactions.signalement",
                    ),
                ),
            ],
            options={
                "db_table": "votes_signalements",
                "unique_together": {("signalement", "citoyen")},
            },
        ),
    ]
