# Generated by Django 5.2.10 on 2026-05-09 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communes", "0003_projet_blockchain_audit_hash_alter_projet_statut"),
        ("transactions", "0007_rapportpdf_projettransaction_votesignalement"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="projet",
            field=models.ForeignKey(
                blank=True,
                help_text="Projet associé à cette transaction (optionnel)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="communes.projet",
            ),
        ),
    ]
