# Generated by Django 5.1.4 on 2026-05-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_signalement_profession"),
        ("transactions", "0008_transaction_projet"),
    ]

    operations = []
