# Generated by Django 5.1.4 on 2026-05-11 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0009_merge_20260511_1859"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="signalement",
            new_name="signalement_created_41ac55_idx",
            old_name="transactions_created_by_prof_idx",
        ),
        migrations.RenameIndex(
            model_name="signalement",
            new_name="signalement_is_revi_3bc6bd_idx",
            old_name="transactions_is_reviewed_idx",
        ),
    ]
