# Generated by Django 5.1.4 on 2026-05-13 02:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communes", "0005_commune_blockchain_tx_hash_dotation"),
        (
            "transactions",
            "0010_rename_transactions_created_by_prof_idx_signalement_created_41ac55_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionDGDDL",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("ENQUETE_LANCEE", "🚨 Enquête lancée"),
                            ("EVIDENCE_ADDED", "📎 Preuve ajoutée"),
                            ("MAIRE_NOTIFIE", "📢 Maire notifié"),
                            ("RESOLUTION", "⚖️ Décision prise"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "actions_dgddl",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommentaireSignalement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contenu", models.TextField()),
                (
                    "type_commentaire",
                    models.CharField(
                        choices=[
                            ("AVIS", "💬 Avis citoyen"),
                            ("JUSTIFICATION", "📝 Justification (Maire)"),
                            ("ENQUETE", "🔍 Note d'enquête (DGDDL)"),
                        ],
                        default="AVIS",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "commentaires_signalements",
                "ordering": ["created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="signalement",
            options={"ordering": ["-is_prioritaire", "-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="signalement",
            name="signalement_is_revi_3bc6bd_idx",
        ),
        migrations.AddField(
            model_name="signalement",
            name="enquete_lancee_a",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="signalement",
            name="enquete_lancee_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enquetes_lancees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="signalement",
            name="is_prioritaire",
            field=models.BooleanField(
                default=False, help_text="≥4 votes = prioritaire"
            ),
        ),
        migrations.AddField(
            model_name="signalement",
            name="resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FRAUDE", "Fraude"),
                    ("FAUX", "Faux"),
                    ("INFONDE", "Infondé"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="signalement",
            name="resolution_a",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="signalement",
            name="resolution_justification",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="signalement",
            name="resolution_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolutions_dgddl",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="signalement",
            name="statut",
            field=models.CharField(
                choices=[
                    ("ACTIF", "🔵 Actif - En vote"),
                    ("ENQUETE_DGDDL", "🟠 Enquête DGDDL"),
                    ("VALIDE_FRAUDE", "🔴 Fraude confirmée"),
                    ("REJETE_FAUX", "⚪ Signalement faux"),
                    ("CLOS", "⚫ Clos"),
                ],
                default="ACTIF",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="signalement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="signalement",
            index=models.Index(fields=["statut"], name="signalement_statut_27f279_idx"),
        ),
        migrations.AddIndex(
            model_name="signalement",
            index=models.Index(
                fields=["-created_at"], name="signalement_created_d8b292_idx"
            ),
        ),
        migrations.AddField(
            model_name="actiondgddl",
            name="effectuee_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="actiondgddl",
            name="signalement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions_dgddl",
                to="transactions.signalement",
            ),
        ),
        migrations.AddField(
            model_name="commentairesignalement",
            name="auteur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commentaires_signalements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="commentairesignalement",
            name="signalement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentaires",
                to="transactions.signalement",
            ),
        ),
    ]
