# Generated by Django 5.2.10 on 2026-05-14 02:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0011_actiondgddl_commentairesignalement_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentaireProposition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contenu", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commentaires_propositions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaires",
                        to="transactions.propositiondepense",
                    ),
                ),
            ],
            options={
                "db_table": "commentaires_propositions",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PreuveProposition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ipfs_hash", models.CharField(max_length=100)),
                ("ipfs_url", models.URLField()),
                (
                    "nom_fichier",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "type_fichier",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("pdf", "PDF"),
                            ("autre", "Autre"),
                        ],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "proposition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preuves",
                        to="transactions.propositiondepense",
                    ),
                ),
            ],
            options={
                "db_table": "preuves_propositions",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
