# Generated by Django 5.2.10 on 2026-05-14 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communes", "0006_projet_budget_consomme_fcfa_and_more"),
        ("transactions", "0012_commentaireproposition_preuveproposition"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="blockchain_synced_at",
        ),
        migrations.AddField(
            model_name="commentaireproposition",
            name="type_commentaire",
            field=models.CharField(
                choices=[
                    ("AVIS", "Avis Citoyen"),
                    ("NOTE_TECHNIQUE", "Note Technique Agent/Maire"),
                ],
                default="AVIS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="propositiondepense",
            name="date_passage_officiel",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="propositiondepense",
            name="deadline_vote_officiel",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="propositiondepense",
            name="is_official",
            field=models.BooleanField(
                default=False, help_text="Validé par le Maire pour vote décisionnel"
            ),
        ),
        migrations.AddField(
            model_name="propositiondepense",
            name="maire_signature_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Preuve blockchain engagement Maire",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="propositiondepense",
            name="resultat_vote_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Preuve blockchain résultat final",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="signalement",
            name="blockchain_tx_hash_enquete",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="signalement",
            name="blockchain_tx_hash_resolution",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="correction_justification",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_correction",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="parent_frauduleux",
            field=models.ForeignKey(
                blank=True,
                help_text="Transaction originale qui a été invalidée par celle-ci",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrections",
                to="transactions.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="actiondgddl",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("ENQUETE_LANCEE", "🚨 Enquête lancée"),
                    ("NOTE_ENQUETE", "📝 Note d'investigation"),
                    ("EVIDENCE_ADDED", "📎 Preuve ajoutée"),
                    ("MAIRE_NOTIFIE", "📢 Maire notifié"),
                    ("RESOLUTION", "⚖️ Décision prise"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="propositiondepense",
            name="statut",
            field=models.CharField(
                choices=[
                    ("SUGGESTION", "Suggestion Citoyenne"),
                    ("OFFICIELLE", "Officielle (Engagement Maire)"),
                    ("APPROUVEE", "Approuvée (Budget Adopté)"),
                    ("REJETEE", "Rejetée"),
                    ("EXPIREE", "Expirée"),
                    ("CONVERTIE", "Convertie en Projet"),
                ],
                default="SUGGESTION",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="signalement",
            name="statut",
            field=models.CharField(
                choices=[
                    ("NOUVEAU", "🆕 Nouveau"),
                    ("ACTIF", "🔵 Actif - En vote"),
                    ("VIRAL", "🔥 Viral - Alerte DGDDL"),
                    ("ENQUETE_DGDDL", "🟠 Enquête DGDDL"),
                    ("VALIDE_FRAUDE", "🔴 Fraude confirmée"),
                    ("REJETE_FAUX", "⚪ Signalement faux"),
                    ("CLOS", "⚫ Clos"),
                ],
                default="NOUVEAU",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="statut",
            field=models.CharField(
                choices=[
                    ("BROUILLON", "Brouillon"),
                    ("SOUMIS", "Soumis (en attente de validation)"),
                    ("VALIDE", "Validé sur blockchain"),
                    ("REJETE", "Rejeté"),
                    ("FRAUDULEUSE", "🚨 Fraude confirmée"),
                    ("CORRIGEE", "✅ Corrigée (Audit)"),
                ],
                default="BROUILLON",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CommentaireProjet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contenu", models.TextField()),
                ("ipfs_hash", models.CharField(blank=True, default="", max_length=100)),
                ("ipfs_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commentaires_projets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaires",
                        to="communes.projet",
                    ),
                ),
            ],
            options={
                "db_table": "commentaires_projets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoteProjet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "citoyen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes_projets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="communes.projet",
                    ),
                ),
            ],
            options={
                "db_table": "votes_projets",
                "unique_together": {("projet", "citoyen")},
            },
        ),
    ]
