# Generated by Django 5.2.10 on 2026-05-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0013_remove_transaction_blockchain_synced_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="blockchain_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
