# Generated by Django 5.2.10 on 2026-05-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0014_transaction_blockchain_synced_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propositiondepense",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("INFRASTRUCTURE", "Infrastructure"),
                    ("SANTE", "Santé"),
                    ("EDUCATION", "Éducation"),
                    ("EAU_ASSAINISSEMENT", "Eau & Assainissement"),
                    ("SECURITE", "Sécurité"),
                    ("ADMINISTRATION", "Administration"),
                    ("AGRICULTURE", "Agriculture"),
                    ("CULTURE_SPORT", "Culture & Sport"),
                    ("ENVIRONNEMENT", "Environnement"),
                    ("SOCIAL", "Social"),
                    ("AUTRE", "Autre"),
                ],
                default="AUTRE",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("INFRASTRUCTURE", "Infrastructure"),
                    ("SANTE", "Santé"),
                    ("EDUCATION", "Éducation"),
                    ("EAU_ASSAINISSEMENT", "Eau & Assainissement"),
                    ("SECURITE", "Sécurité"),
                    ("ADMINISTRATION", "Administration"),
                    ("AGRICULTURE", "Agriculture"),
                    ("CULTURE_SPORT", "Culture & Sport"),
                    ("ENVIRONNEMENT", "Environnement"),
                    ("SOCIAL", "Social"),
                    ("AUTRE", "Autre"),
                ],
                default="AUTRE",
                max_length=50,
            ),
        ),
    ]
