# Generated by Django 5.2.10 on 2026-05-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0015_alter_propositiondepense_categorie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentaireproposition",
            name="image_url",
            field=models.URLField(
                blank=True, default="", help_text="Lien IPFS de l'image jointe"
            ),
        ),
        migrations.AddField(
            model_name="commentairesignalement",
            name="image_url",
            field=models.URLField(
                blank=True, default="", help_text="Lien IPFS de l'image jointe"
            ),
        ),
    ]
