# Generated by Django 5.2.10 on 2026-05-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0016_commentaireproposition_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propositiondepense",
            name="budget_alloue_fcfa",
            field=models.BigIntegerField(
                default=0,
                help_text="Budget officiel fixé par le Maire lors de l'officialisation",
            ),
        ),
    ]
