# Generated by Django 5.1.4 on 2026-05-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("nom", models.CharField(max_length=200)),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("ABIDJAN", "Abidjan"),
                            ("BOUAKE", "Bouaké"),
                            ("YAMOUSSOUKRO", "Yamoussoukro"),
                            ("DALOA", "Daloa"),
                            ("SAN_PEDRO", "San-Pédro"),
                            ("KORHOGO", "Korhogo"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=50,
                    ),
                ),
                ("population", models.PositiveIntegerField(default=0)),
                ("superficie_km2", models.FloatField(default=0)),
                ("budget_annuel_fcfa", models.BigIntegerField(default=0)),
                ("maire_nom", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Commune",
                "verbose_name_plural": "Communes",
                "db_table": "communes",
                "ordering": ["nom"],
            },
        ),
    ]
