# Generated by Django 5.2.10 on 2026-05-09 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("budget_alloue_fcfa", models.BigIntegerField(default=0)),
                ("taux_execution", models.FloatField(default=0.0)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("EN_ATTENTE", "En attente"),
                            ("EN_COURS", "En cours"),
                            ("ACHEVE", "Achevé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bailleur",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "BAILLEUR"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projets_finances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projets",
                        to="communes.commune",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "db_table": "projets",
            },
        ),
    ]
