# Generated by Django 5.2.10 on 2026-05-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communes", "0002_projet"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="blockchain_audit_hash",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="projet",
            name="statut",
            field=models.CharField(
                choices=[
                    ("BROUILLON", "Brouillon"),
                    ("EN_ATTENTE", "En attente"),
                    ("EN_COURS", "En cours"),
                    ("ACHEVE", "Achevé"),
                    ("ANNULE", "Annulé"),
                    ("SOUS_ENQUETE", "Sous enquête DGDDL"),
                ],
                default="EN_ATTENTE",
                max_length=20,
            ),
        ),
    ]
