# Generated by Django 5.2.10 on 2026-05-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communes", "0003_projet_blockchain_audit_hash_alter_projet_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="score_transparence",
            field=models.PositiveIntegerField(default=0, help_text="Score de 0 à 100"),
        ),
    ]
