# Generated by Django 5.2.10 on 2026-05-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communes", "0004_commune_score_transparence"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="blockchain_tx_hash_dotation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hash de la transaction blockchain de dotation",
                max_length=100,
            ),
        ),
    ]
