# Generated by Django 5.2.10 on 2026-05-14 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communes", "0005_commune_blockchain_tx_hash_dotation"),
        ("transactions", "0012_commentaireproposition_preuveproposition"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="budget_consomme_fcfa",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projet",
            name="parent_proposition",
            field=models.ForeignKey(
                blank=True,
                help_text="Idée citoyenne à l'origine de ce projet",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projets_generes",
                to="transactions.propositiondepense",
            ),
        ),
    ]
